# Generated by Django 5.0.1 on 2024-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='user_type',
            field=models.CharField(choices=[('EIT', 'Eit'), ('TEACHING_FELLOW', 'Teaching Fellow'), ('ADMIN_STAFF', 'Admin Staff'), ('ADMIN', 'Admin'), ('SUPER_USER', 'Super User')], max_length=20),
        ),
    ]
