# Generated by Django 5.0.1 on 2024-02-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_imuser_middle_name_alter_imuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
