# Generated by Django 5.0.1 on 2024-02-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_course_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
