# Generated by Django 5.0.1 on 2024-02-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_author', to='users.imuser'),
        ),
        migrations.AlterField(
            model_name='cohortmember',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cohort_memberships', to='users.imuser'),
        ),
        migrations.AlterField(
            model_name='cohortmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_memberships', to='users.imuser'),
        ),
    ]
