# Generated by Django 5.0.1 on 2024-02-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classschedule_classattendance_query_querycomment'),
        ('users', '0005_alter_cohort_author_alter_cohortmember_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_schedule', to='users.imuser'),
        ),
        migrations.AlterField(
            model_name='query',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_queries', to='users.imuser'),
        ),
        migrations.AlterField(
            model_name='query',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_queries', to='users.imuser'),
        ),
        migrations.AlterField(
            model_name='query',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_queries', to='users.imuser'),
        ),
        migrations.AlterField(
            model_name='querycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_query_comments', to='users.imuser'),
        ),
    ]
