# Generated by Django 5.0.2 on 2024-02-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_classschedule_course_classschedule_facilitator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
